name: Test publish

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stag
          - main
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.x
  ENV: 'DEV'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - name: test 0
        run: echo ${{ inputs.mode }}
      - name: test
        run: echo ${GITHUB_REF#refs/heads/}
      - name: Build SvelteKit according to branch
        id: env
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          case "$BRANCH_NAME" in
            "dev")
              echo "env=DEV" >> "$GITHUB_OUTPUT"
              ;;
            "staging")
              echo "env=STAGING" >> "$GITHUB_OUTPUT"
              ;;
            "main")
              echo "env=PROD" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "env=DEV" >> "$GITHUB_OUTPUT"
              ;;
          esac

  publish:
    runs-on: ubuntu-latest
    needs: set-env
    environment: ${{needs.set-env.outputs.env}}
    steps:
      - name: test
        run: |
          if [ ${{ secrets.NOME }} == "PROD" ]; then
            echo 'funfou'
          else
            echo "N FUNFOU"
          fi

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: test
        run: git log -1 --date=iso -- "package.json"
      - name: Install publisher
        run: npm install -g @vscode/vsce
      - name: Compile
        run: vsce package
      - name: publish
        run: vsce publish -p "${{ secrets.VSCODE_PAT }}"
