name: Test Notify

on:
  workflow_run:
    workflows:
      - Test publish
    types:
      - completed

permissions:
  actions: read

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "${ toJson(github.event.workflow_run) }"